const api = {
  aura: { title: "Aura", tone: "coral", description: "Decorators for healing, observing, validating, and controlling Python calls.", members: [
    ["heal", "Diagnose failures, retry them, and preserve the original exception.", "@aura.heal(retries=1)\ndef add(a, b): return a + b"], ["patch", "Request a source repair, validate it, and execute it in a small namespace.", "@aura.patch()\ndef value(): return 7"], ["retry", "Retry transient network-like errors while failing fast on logic errors.", "@aura.retry(retries=2)\ndef fetch(): return \"ready\""], ["validate", "Validate arguments and return values using Pydantic or dictionary schemas.", "@aura.validate(output_schema=dict)\ndef result(): return {\"ok\": True}"], ["trace", "Log arguments, result, exception, and elapsed time as structured data.", "@aura.trace\ndef greet(name): return f\"Hi {name}\""], ["cache", "Memoize results, optionally normalizing string whitespace for near matches.", "@aura.cache(semantic=True)\ndef clean(text): return text.strip()"], ["async_heal", "Async counterpart to heal for coroutine functions.", "@aura.async_heal()\nasync def work(): return \"done\""], ["sandbox", "Run a function with a restricted builtins mapping when it accepts no globals.", "@aura.sandbox\ndef safe_sum(): return sum(range(4))"], ["explain", "Attach a plain-English explanation to exceptions as a note.", "@aura.explain\ndef fail(): raise ValueError(\"demo\")"], ["benchmark", "Measure wrapper overhead and function duration in a structured log.", "@aura.benchmark\ndef calculate(): return sum(range(10))"], ["guard", "Block a call with a clear message when prerequisites are absent.", "@aura.guard(env=())\ndef run(): return \"allowed\""], ["dry_run", "Mark a call as dry-run and expose intercepted side-effect names to logs.", "@aura.dry_run()\ndef publish(): return \"preview\""], ["audit", "Write calls, failures, and successful results to a JSON-lines audit log.", "@aura.audit(path=\"/tmp/godaix.jsonl\")\ndef save(): return True"], ["fallback", "Return a fallback function or default value after the primary fails.", "@aura.fallback(default=\"offline\")\ndef provider(): raise OSError()"], ["rate_limit", "Throttle calls using a token bucket shared by one decorated function.", "@aura.rate_limit(rate=2, capacity=1)\ndef call(): return \"ok\""],
  ] },
  nexus: { title: "Nexus", tone: "violet", description: "Direct-call coding analysis helpers with useful offline behavior.", members: [
    ["explain", "Turn an exception or traceback into a concise plain-English diagnosis.", "nexus.explain(KeyError(\"name\"))"], ["parse", "Extract schema-shaped data from text, using JSON-like key matching offline.", "nexus.parse(\"name: Ada\", Person)"], ["agent", "Inspect a project and optionally apply narrowly scoped provider-generated edits.", "nexus.agent(\"inspect\", \".\", allow_edits=False)"], ["summarize", "Summarize functions, classes, imports, and the public shape of Python code.", "nexus.summarize(\"def hello(): return 1\")"], ["review", "Return concrete review comments for risky unified-diff patterns.", "nexus.review(\"+ eval(user_input)\")"], ["test_gen", "Generate a runnable pytest skeleton from a callable's signature.", "nexus.test_gen(my_function)"], ["docstring", "Generate a concise docstring from a function signature and body.", "nexus.docstring(my_function)"], ["translate", "Provide a provider-backed translation request with a useful offline marker.", "nexus.translate(\"x = 1\", \"javascript\")"], ["refactor", "Suggest a refactor toward a stated goal while preserving the input code offline.", "nexus.refactor(\"x=1\", \"clarity\")"], ["complexity", "Estimate cyclomatic complexity fully offline from Python syntax.", "nexus.complexity(\"def f(x):\\n if x: return 1\")"], ["security_scan", "Flag high-signal insecure constructs offline and request deeper review when online.", "nexus.security_scan(\"password = 'secret'\")"], ["dependency_check", "Find imports in a file and list likely missing requirements entries.", "nexus.dependency_check(\"module.py\")"], ["commit_message", "Generate a conventional commit subject from a diff.", "nexus.commit_message(\"fix timeout\")"], ["changelog", "Format commit subjects as a compact changelog entry.", "nexus.changelog([\"fix timeout\"])"], ["ask", "Answer a question scoped strictly to supplied codebase context.", "nexus.ask(\"What is this?\", \"x = 1\")"],
  ] },
  aether: { title: "Aether", tone: "blue", description: "Bounded resilience, offline operation, and performance utilities.", members: [
    ["timeout", "Enforce a deadline for a callable or context-managed operation.", "@aether.timeout(1)\ndef fast(): return \"ok\""], ["circuit_breaker", "Open a provider circuit after consecutive failures for a cooldown.", "breaker = aether.circuit_breaker(\"api\")\nbreaker.call(fetch)"], ["offline_queue", "Persist failed JSON requests in SQLite for later replay.", "queue = aether.offline_queue(\"queue.sqlite3\")\nqueue.put({\"x\": 1})"], ["heuristics", "Diagnose common Python exceptions without network access.", "aether.heuristics(KeyError(\"x\"))"], ["fallback_provider", "Try configured providers in order and return the first successful result.", "aether.fallback_provider([local, hosted])"], ["degraded_mode", "Detect unavailable network and log a clear degraded-mode warning.", "is_offline = aether.degraded_mode()"], ["lazy_load", "Import a heavy module only when requested and optionally return an attribute.", "json = aether.lazy_load(\"json\")"], ["zero_overhead", "Benchmark a decorated fast path and return measured per-call overhead.", "aether.zero_overhead(iterations=100)"], ["network_probe", "Measure connection latency and recommend bounded retry settings.", "aether.network_probe(\"127.0.0.1\", 9)"], ["missing_dependency_helper", "Raise an actionable installation message for an expected package.", "aether.missing_dependency_helper(\"json\")"], ["cache_store", "Provide bounded TTL caching for diagnosis and patch results in memory and JSON.", "store = aether.cache_store(\"cache.json\")\nstore.put(\"x\", 1)"], ["debounce", "Suppress identical error-trigger calls inside a time window.", "@aether.debounce(10)\ndef notify(): return True"], ["status", "Return current provider, connectivity, degradation, and circuit status.", "aether.status()"], ["rust_core", "Use a future compiled extension when present, otherwise reference Python.", "aether.rust_core(\"sum\", [1, 2])"], ["config", "Centralize timeout, retry, circuit, and cache settings.", "settings = aether.config()\nsettings.as_dict()"],
  ] },
  apex: { title: "Apex", tone: "gold", description: "Integrations and operational tooling for teams.", members: [
    ["pytest_plugin", "Return a pytest hook plugin that diagnoses failed test reports.", "pytest_plugins = [apex.pytest_plugin()]"], ["pre_commit_hook", "Review staged Python diffs and return a hook-compatible status code.", "exit_code = apex.pre_commit_hook([])"], ["github_action", "Post review suggestions to GitHub using a token supplied by the environment.", "apex.github_action(diff, issue=42)"], ["django_middleware", "Create Django middleware that logs diagnosis and re-raises exceptions.", "Middleware = apex.django_middleware(get_response)"], ["flask_middleware", "Register a Flask exception handler with a plain-English diagnosis.", "apex.flask_middleware(app)"], ["fastapi_middleware", "Add FastAPI middleware that observes unhandled failures.", "apex.fastapi_middleware(app)"], ["cli", "Run fix, explain, or agent commands from a small standard-library CLI.", "apex.cli([\"explain\", \"bad input\"])"], ["vscode_extension", "Serve a documented JSON-RPC-style endpoint for a future editor extension.", "apex.vscode_extension(host=\"127.0.0.1\", port=8765)"], ["redact", "Remove likely secrets and PII before code leaves the process.", "safe = apex.redact(\"api_key=secret\")"], ["on_prem", "Describe a self-hosted provider endpoint without contacting it.", "apex.on_prem(\"http://localhost:8000\")"], ["multi_tenant", "Manage named tenant keys and in-process usage counters.", "tenants = apex.multi_tenant()\ntenants.add(\"team\", \"key\")"], ["shared_cache", "Return a cache adapter using a supplied shared backend or local dictionary.", "cache = apex.shared_cache()\ncache[\"put\"](\"x\", 1)"], ["metrics", "Expose Prometheus-compatible counters and latency observations.", "metrics = apex.metrics()\nmetrics.observe(\"heal\", .01)"], ["dashboard", "Render a minimal local HTML dashboard from audit events.", "html = apex.dashboard(\"godaix-audit.jsonl\")"], ["docker_ready", "Validate environment-only container configuration without prompting.", "apex.docker_ready(required=())"],
  ] },
  aix: { title: "Aix", tone: "green", description: "Context managers for block-level repair, diagnosis, safe execution, and operational control.", members: [
    ["fix", "Capture only the failing block, validate a fenced-free repair, execute it, and print its output.", "with aix.fix():\n    result = 10 / 0"],
    ["explain", "Print a plain-English diagnosis for an exception inside a block.", "with aix.explain():\n    parse_record()"],
    ["snippet", "Report the exact failing line range and a targeted patch.", "with aix.snippet():\n    total = values[9]"],
    ["diff", "Show a unified diff between the original and repaired block.", "with aix.diff():\n    return missing_name"],
    ["file_patch", "Print a full proposed file when a fix needs code outside the block.", "with aix.file_patch():\n    call_helper()"],
    ["retry", "Retry transient block failures with configurable exponential backoff.", "with aix.retry(attempts=3):\n    fetch_remote()"],
    ["fallback", "Provide a default value after a block fails.", "with aix.fallback(default=[]):\n    load_items()"],
    ["dry", "Describe and intercept side-effecting operations for a safe dry run.", "with aix.dry():\n    publish_report()"],
    ["sandbox", "Run a block with a restricted execution context.", "with aix.sandbox():\n    calculate_score()"],
    ["guard", "Check environment variables and packages before entering a block.", "with aix.guard(env=(\"MODE\",)):\n    start_service()"],
    ["trace", "Log timing and the failing frame for a block.", "with aix.trace():\n    transform_batch()"],
    ["benchmark", "Measure the execution time of an arbitrary block.", "with aix.benchmark():\n    sort_records()"],
    ["audit", "Append block exceptions and source locations to an audit log.", "with aix.audit(path=\"audit.log\"):\n    authorize()"],
    ["rate_limit", "Throttle repeated provider calls made by a block.", "with aix.rate_limit(interval=1):\n    ask_model()"],
    ["repl", "Offer an interactive, backed-up source-file application after showing a fix.", "with aix.repl():\n    broken_step()"],
  ] },
};
const $ = (selector) => document.querySelector(selector);
const providers = ["offline", "openai", "anthropic", "gemini", "groq", "ollama", "openrouter", "qwen", "xai", "openai_compatible"];
function renderProviders() { $("#provider-grid").innerHTML = providers.map((provider, index) => `<div class="provider-pill"><span class="provider-number">${String(index + 1).padStart(2, "0")}</span><strong>${provider}</strong><code>${provider === "offline" ? "no key required" : "GODAIX_PROVIDER=" + provider}</code></div>`).join(""); }
function renderApi(filter = "") { const needle = filter.toLowerCase().trim(); let matches = 0; $("#api-list").innerHTML = Object.entries(api).map(([key, group]) => { const entries = group.members.filter(([name, description, example]) => !needle || `${key} ${name} ${description} ${example}`.toLowerCase().includes(needle)); matches += entries.length; if (!entries.length) return ""; return `<section class="api-group" id="${key}"><div class="api-group-head"><div><span class="module-dot ${group.tone}"></span><h3>${group.title}</h3></div><span>${entries.length} / 15</span></div><p class="group-description">${group.description}</p><div class="api-cards">${entries.map(([name, description, example]) => { const output = example.includes("raise") || example.includes("/ 0") ? "The example reports the handled exception and its diagnosis." : `The example completes ${key}.${name} and returns its documented result.`; return `<article class="api-card"><div class="api-name"><code>${key}.${name}</code><span>PUBLIC</span></div><p class="card-teaser">${description}</p><button class="view-example" type="button" aria-expanded="false">View example ▸</button><div class="card-details" hidden><p>${description} This keeps the operation focused on the call or block shown here, while leaving provider configuration and side effects under the caller's control.</p><pre><code>${escapeHtml(example)}</code></pre><p class="output-label">Output:</p><pre class="output"><code>${escapeHtml(output)}</code></pre><button class="copy-button" data-copy="${escapeAttr(example)}">Copy example</button></div></article>`; }).join("")}</div></section>`; }).join(""); $("#no-results").hidden = matches !== 0; document.querySelectorAll(".view-example").forEach((button) => button.addEventListener("click", () => { const details = button.nextElementSibling; const expanded = button.getAttribute("aria-expanded") === "true"; button.setAttribute("aria-expanded", String(!expanded)); button.textContent = expanded ? "View example ▸" : "Hide example ▾"; details.hidden = expanded; })); document.querySelectorAll(".copy-button").forEach((button) => button.addEventListener("click", () => copyText(button.dataset.copy, button))); }
function escapeHtml(value) { return value.replaceAll("&", "&amp;").replaceAll("<", "&lt;").replaceAll(">", "&gt;"); }
function escapeAttr(value) { return value.replaceAll("&", "&amp;").replaceAll('"', "&quot;").replaceAll("<", "&lt;"); }
function copyText(text, button) { navigator.clipboard?.writeText(text); const original = button.textContent; button.textContent = "Copied"; setTimeout(() => { button.textContent = original; }, 1000); }
$("#search-input").addEventListener("input", (event) => renderApi(event.target.value));
$("#menu-toggle").addEventListener("click", () => $("#sidebar").classList.toggle("open"));
document.querySelectorAll(".sidebar a").forEach((link) => link.addEventListener("click", () => $("#sidebar").classList.remove("open")));
document.querySelectorAll("[data-copy]").forEach((button) => button.addEventListener("click", () => copyText(button.dataset.copy, button)));
renderProviders(); renderApi();
