from __future__ import annotations

import json
import os
import subprocess
import sys
from pathlib import Path

from god_ai import aura


def scaffold_project(project_name: str, root: Path | None = None) -> dict[str, object]:
    target = (root or Path.cwd()) / project_name
    target.mkdir(parents=True, exist_ok=True)
    (target / "index.html").write_text("<!doctype html><html><body><h1>Hello from God AI</h1></body></html>", encoding="utf-8")
    (target / "styles.css").write_text("body{font-family:sans-serif;display:grid;place-items:center;height:100vh;}", encoding="utf-8")
    (target / "app.js").write_text("document.body.insertAdjacentHTML('beforeend', '<p>Generated by God AI</p>');", encoding="utf-8")
    return {"path": str(target), "files": ["index.html", "styles.css", "app.js"]}


if __name__ == "__main__":
    project = scaffold_project("demo_web_app", Path(__file__).resolve().parent)
    print(json.dumps(project, indent=2))
